### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by fclesio** [xqnwang/conformalForecast#1]
Hello! 

First of all thanks for the great library and the effort placed into it. 

Is there any intention in the future to change that license from GPL-3 to a more permissive one (e.g. MIT)? 

I really would like to have a shot, but in most domains that I am experimenting with right now this license is not recommended due to its virality and unknown legal scenarios.

Thanks!

**Comment by xqnwang** [comment]
Hi Flavio! We will be keeping the GPL-3 license at this stage, as it is a commonly used license for open-source software.

**Comment by fclesio** [comment]
Thanks for the prompt answer @xqnwang. 

Of course, you and @robjhyndman are entitled to choose whatever license you want for the project. Said that (and only for my understanding) what's the rationale to keep it as GPL-3 in face of other OSS licences like Apache or MIT?

**Comment by robjhyndman** [comment]
GPL is a very liberal licence, allowing you to do almost anything you want with the package. You can use it for commercial purposes. You can modify it and redistribute the modified version (provided you keep the licence). About the only thing you can't do is re-sell it. It is also one of the most widely used OSS licences. So I'm puzzled why it is a problem to you. What do you want to do with the package that is not allowed under GPL?

**Comment by fclesio** [comment]
Thank you for your response, @robjhyndman!

In the industry, the use of the GPL license is often discouraged or even prohibited by some companies due to its viral nature and the uncertain legal implications it may pose in legal disputes.

Most packages used in the industry are licensed under Apache, MIT, or BSD-3 licenses.

**Comment by robjhyndman** [comment]
Perhaps your industry has different requirements from others. My forecast package uses a GPL licence; it is used in hundreds of thousands of organizations around the world, with 3 million downloads per year. It has been using the GPL licence for nearly 20 years without a single person raising a concern.

**Comment by robjhyndman** [comment]
Distribution of licences used by R packages: https://thinkr-open.github.io/licensing-r/cran-licenses.html#the-ten-most-used

**Comment by fclesio** [comment]
For the respect that I have for your public work I’ll abstract the tone used and I consider my question answered. 

Thank you and have a great day.
